CREATE TABLE GTT_CAMPAIGN_ACCOUNTS (
    ILOAN_MASTER_ID numeric(20, 0),
    VCONTRACTNO varchar(100),
    IPRODUCT_ID numeric(20, 0),
    VPRODUCT_NAME varchar(100),
    ILOAN_PRODUCT_ID numeric(20, 0),
    IGRAND_PARENTAL_STATUS_ID numeric(20, 0),
    IGRAND_PARENTAL_STATUS varchar(100),
    IPARENTAL_STATUS_ID numeric(20, 0),
    IPARENTAL_STATUS varchar(100),
    IC121_STATUS_ID numeric(20, 0),
    IC121_STATUS varchar(100),
    VACTIVE_PTP_ARR char(1),
    DPTP_DATE datetime2,
    DARR_DATE datetime2,
    DREVIEW_DATE datetime2,
    ICAMPAIGN_SECTION_ID numeric(20, 0),
    CAMPAIGN_NOTE varchar(1000),
    IDELIQUENT_ID numeric(20, 0),
    IDPD int,
    IARR_ADV_AMT numeric(20, 2),
    IOS_BALANCE numeric(20, 2),
    VMOB_PHN_NO_1 varchar(800),
    IDAYS_SINCE_LAST_RPC numeric(6, 0),
    IDAYS_IN_COLLECTION numeric(6, 0),
    ACCOUNT_UNAPPROVED char(1),
    LAST_PAY_DATE datetime2,
    LOAN_EXP_DATE datetime2,
    DSNAPSHOT_DATE datetime2,
    IBRANCH_ID numeric(20, 0),
    BRANCH_CODE varchar(100),
    FACILITY_PERIOD numeric(20, 2),
    BALANCE_RENTALS numeric(20, 2),
    CARD_LIMIT numeric(20, 2),
    ACCOUNT_STATUS numeric(20, 0),
    WRITTEN_OFF_FLAG numeric(20, 0),
    MORATORIUM_FLAG numeric(20, 0),
    CENTRAL_RECOVERY_FLAG numeric(20, 0),
    BRANCH_RECOVERY_FLAG numeric(20, 0),
    NPA_FLAG numeric(20, 0),
    SETTLEMENT_FLAG varchar(10),
    VVIP_FLAG numeric(10, 0),
    NEXT_INSTALLMENT_DATE datetime2,
    LAST_INSTALLMENT_STATUS varchar(50),
    LAST_INSTALLMENT_DATE datetime2,
    SET_DREVIEW_DATE datetime2,
    DAYS_CHEQUE_RETURN numeric(20, 0),
    DAYS_INVOICE_NOTPAID numeric(20, 0),
    VAPPROVED_SET_PLAN char(1),
    REALLOCATION_FLAG varchar(1),
    SET_PRE_DREVIEW_DATE date,
    IARR_MIN_AMT numeric(22, 2),

);






