CREATE TABLE TBL_MONTH_SUMMARY (
    REC_ID varchar(50),
    YEAR numeric(6, 0),
    MONTH varchar(20),
    CONTRACT_NO varchar(200),
    LOANMASTER_ID numeric(20, 0),
    ME_USERNAME varchar(100),
    ME_AD varchar(100),
    MONTH_START_STATUS varchar(100),
    MONTH_END_STATUS varchar(100),
    LOAN_EXPIRE_DATE date,
    LOAN_START_DATE datetime2,
    LOAN_AMOUNT decimal(20, 2),
    PRODUCT_ID numeric(20, 0),
    PRODUCT_NAME varchar(50),
    LOAN_PRODUCT_ID numeric(20, 0),
    LOAN_PRODUCT_NAME varchar(100),
    MONTH_START_DPD_DATE date,
    MONTH_START_DPD decimal(10, 2),
    MONTH_MAX_DPD decimal(10, 2),
    MONTH_END_DPD_DATE date,
    MONTH_END_DPD decimal(20, 2),
    MONTH_START_ARR decimal(20, 2),
    MONTH_MAX_ARR decimal(20, 2),
    MONTH_END_ARR decimal(20, 2),
    CAMPAIGN_START varchar(100),
    CAMPAIGN_END varchar(100),
    BUCKET_START varchar(100),
    BUCKET_END varchar(100),
    MONTH_START_BALANCE decimal(20, 2),
    MONTH_END_BALANCE decimal(20, 2),
    MONTH_TOTAL_PAYMENT decimal(20, 2),
    MONTH_ACTIONS int,
    MONTH_ACCESS int,
    MONTH_CALL_COUNT int,
    MONTH_RPC int,
    MONTH_NRPC int,
    MONTH_FIELD_VISITS int,
    MONTH_PTP_COUNT int,
    MONTH_PTP_AMOUNT decimal(20, 2),
    PTP_KEPT_COUNT_IN_MONTH numeric(6, 0),
    PTP_KEPT_AMOUNT_IN_MONTH decimal(20, 2),
    PTP_BROKEN_COUNT_IN_MONTH numeric(6, 0),
    PTP_BROKEN_AMOUNT_IN_MONTH decimal(20, 2),
    PTP_KEPT_COUNT_FOR_MONTH numeric(6, 0),
    PTP_KEPT_AMOUNT_FOR_MONTH decimal(20, 2),
    PTP_BROKEN_COUNT_FOR_MONTH numeric(6, 0),
    PTP_BROKEN_AMOUNT_FOR_MONTH decimal(20, 2),
    MONTH_ARR_COUNT numeric(6, 0),
    MONTH_ARR_AMOUNT decimal(20, 2),
    ARR_KEPT_COUNT_IN_MONTH numeric(6, 0),
    ARR_KEPT_AMOUNT_IN_MONTH decimal(20, 2),
    ARR_BROKEN_COUNT_IN_MONTH numeric(6, 0),
    ARR_BROKEN_AMOUNT_IN_MONTH decimal(20, 2),
    ARR_KEPT_COUNT_FOR_MONTH numeric(6, 0),
    ARR_KEPT_AMOUNT_FOR_MONTH decimal(20, 2),
    ARR_BROKEN_COUNT_FOR_MONTH numeric(6, 0),
    ARR_BROKEN_AMOUNT_FOR_MONTH decimal(20, 2),
    BRANCH_ID numeric(20, 0),
    UPDATED_DATE datetime2,
    RUN_DATE datetime2,
    CREATED_DATE datetime2,
    IMONTHSTARTOS decimal(20, 2),
    IMONTHENDOS decimal(20, 2),
    IMONTHMAXOS decimal(20, 2),
    IMONTHSTARTMINARR decimal(20, 2),
    IMONTHENDMINARR decimal(20, 2),
    IMONTHMAXMINARR decimal(20, 2),
    REGIONID numeric(20, 0),
    NPSTATUS varchar(50),
    OFFICE_CODE varchar(100),
    CUSTOMERID numeric(20, 0),

);






