CREATE TABLE TBL_C_EX_AGENCY_CASE (
    IID numeric(20, 0),
    ILOANMASTERID numeric(20, 0),
    IAGENCYID numeric(10, 0),
    VCASEID varchar(100),
    VBATCHTYPE varchar(100),
    VBATCHNO varchar(100),
    IMINAMOUNT numeric(20, 2),
    IARREASAMOUNT numeric(20, 2),
    IINTERESTAMOUNT numeric(20, 2),
    IOUTSTANDAMOUNT numeric(20, 2),
    DASSIGNDATE datetime2,
    DRELEASEDATE datetime2,
    ITOCOLLECTAMOUNT numeric(20, 2),
    ICOLLECTEDAMOUNT numeric(20, 2),
    INOOFDAYS numeric(10, 0),
    VSTATUS varchar(100),
    IVERIFIED numeric(1, 0),
    IVERIFIEDBY numeric(20, 0),
    DVERIFIEDDATE datetime2,
    IAPPROVED numeric(1, 0),
    IAPPROVEDBY numeric(20, 0),
    DAPPROVEDDATE datetime2,
    IRETURN numeric(1, 0),
    IRETURNBY numeric(20, 0),
    DRETURNDATE datetime2,
    IRECALLED numeric(1, 0),
    IRECALLEDBY numeric(20, 0),
    DRECALLEDDATE datetime2,
    IREAPPROVED numeric(1, 0),
    IREAPPROVEDBY numeric(20, 0),
    DREAPPROVEDDATE datetime2,
    IDELIND numeric(1, 0),
    DDELETEDDATE datetime2,
    IPUBLISH numeric(1, 0),
    IADDEDBY numeric(20, 0),
    DADDEDDATE datetime2,
    IUPDATEDBY numeric(20, 0),
    DUPDATEDATE datetime2,
    VURL varchar(1000),
    BATCHID numeric(20, 0),
    REALLOCATED numeric(20, 0),
    ALLOCATIONTYPEID numeric(20, 0),
    ACTIONSTATUS numeric(20, 0),
    STATUSUPDATEDBY numeric(20, 0),
    STATUSUPDATEDDATE datetime2,

);






