CREATE TABLE TBL_C_WK_CASE_FORM (
    IID numeric(20, 0),
    ICASEDTLID numeric(20, 0),
    ILOAN_MASTER_ID numeric(20, 0),
    VCONTRACTNO varchar(1000),
    VCLIENTNAME varchar(1000),
    VTITLE varchar(500),
    VCUSTTITLE varchar(500),
    VCUSTNAMEINITIALS varchar(4000),
    VCUSTLASTNAME varchar(500),
    VCUSTNIC varchar(500),
    VCUSTADDRESS varchar(1000),
    VCUSTALTADDRESS varchar(1000),
    IDPD numeric(20, 0),
    IARREARS numeric(20, 2),
    VDESC text,
    IDELIND numeric(1, 0),
    DDELETEDDATE datetime2,
    IPUBLISH numeric(1, 0),
    IADDEDBY numeric(20, 0),
    DADDEDDATE datetime2,
    IUPDATEDBY numeric(20, 0),
    DUPDATEDATE datetime2,
    VURL varchar(1000),
    VLETTERREQTYPECODE varchar(1000),
    VDATEGRANTED varchar(500),
    VAMOUNTFINANCED varchar(500),
    ITOTALOSAMOUNT numeric(20, 2),
    ICAPITALOSAMOUNT numeric(20, 2),
    IINTERESTOSAMOUNT numeric(20, 2),
    ILATEPAYFEE numeric(20, 2),
    DLATEPAYDATE datetime2,
    VCOMMENT text,
    VREMINDERREFTYPE varchar(200),
    VREMINDERREFOPERATION numeric(20, 2),
    VREMINDERREFSECTION varchar(200),
    IAGENTUSERID numeric(20, 2),
    DFIELDVISITDATE datetime2,
    VFACILITYTYPE varchar(500),
    VVEHICLENO varchar(500),
    VVEHICLELOCATION varchar(500),
    VVEHICLEMAKE varchar(500),
    VVEHICLEMODEL varchar(500),
    VVEHICLECOLOR varchar(500),
    VVEHICLEENGINENO varchar(500),
    VVEHICLECHASSISNO varchar(500),
    VVEHICLEREFNO varchar(500),
    VSEIZERNAME varchar(500),
    VSEIZERADDRESS varchar(500),
    VNOTENO varchar(1000),
    VASSETTYPE varchar(500),
    VSECURITY varchar(500),
    IRNTLDUEPAYMENT numeric(20, 2),
    DRNTLRECOVEREDDATE datetime2,
    IRNTLARREARS numeric(20, 2),
    IRNTLAMOUNT numeric(20, 2),
    IFUTUREUNPAIDRNTL numeric(20, 2),
    IINSURANCESTATUS numeric(20, 2),
    VCOMPANY varchar(500),
    VPOLICYNO varchar(500),
    VRECOMMENDATION varchar(500),
    VBRANCH varchar(500),
    IREQUESTEDBY numeric(20, 0),
    DREQUESTEDDATE datetime2,
    VAGREEMENTNO varchar(1000),
    DLETTERDATE datetime2,
    DREFLETTERDATE datetime2,
    VREFERENCE varchar(4000),
    VLETTERRECEPIENT varchar(500),
    VRECEPIENTNAME varchar(1000),
    VRECEPIENTADDRESS varchar(1000),
    DBALANCEASAT datetime2,
    IAMOUNTGRANTED numeric(20, 2),
    ITOTCAPITALINTFEE numeric(20, 2),
    VPRESENTCARDSTATUS varchar(500),
    IFINALSETTLEMENTAMT numeric(20, 2),
    ILOANAMOUNT numeric(20, 2),
    VPASTDUEPERIOD varchar(500),
    VOFFICEADDRESS varchar(4000),
    DNOTDATE datetime2,
    INOTAMOUNT numeric(20, 2),
    DLOTDATE datetime2,
    DONBEFOREDATE datetime2,
    IMONTHLYINS numeric(20, 2),
    ISUMPAYABLE numeric(20, 2),
    ILASTPAYAMT numeric(20, 2),
    DLASTPAYDATE datetime2,
    VGUARANTORLST varchar(4000),
    VCUSTADDRESS1 varchar(1000),
    VCUSTADDRESS2 varchar(1000),
    VCUSTADDRESS3 varchar(1000),
    VCUSTADDRESS4 varchar(1000),
    VSEIZERADDRESS1 varchar(1000),
    VSEIZERADDRESS2 varchar(1000),
    VSEIZERADDRESS3 varchar(1000),
    VSEIZERADDRESS4 varchar(1000),

);






