CREATE TABLE TBL_C_DP_YARD_VEHICLE_MAIN (
    IID int,
    ILOANMASTERID decimal(20, 0),
    VVEHICLENO varchar(100),
    IFIRSTYARDID numeric(20, 0),
    DFIRSTYARDDATE datetime2,
    IYARDID numeric(20, 0),
    ISEIZERID numeric(20, 0),
    IYARD_FEES numeric(20, 2),
    ISEIZE_CHARGES numeric(20, 2),
    DYARDDATE datetime2,
    VLOCATIONREMARK varchar(1000),
    VREPOMETHOD varchar(100),
    VYARDINMETHOD varchar(100),
    DMAINYARDRETURNDATE datetime2,
    VCUSTOMERCONSENT varchar(10),
    V12IVCONFIRMATION varchar(10),
    DREVENUEEXPIREDATE datetime2,
    DINSURANCEEXPIREDATE datetime2,
    VBONDEDTYPE varchar(10),
    VREMARK varchar(1000),
    VINVENTORY varchar(10),
    VINVENTORYCODE varchar(10),
    VKEY varchar(10),
    VEMISSIONTEST varchar(10),
    VDUPLICATEKEY varchar(10),
    VMILAGE varchar(10),
    VYARDSTATUS varchar(1000),
    VSTEP varchar(1000),
    VBM_OBJECTION_DISPOSAL varchar(10),
    VYARD_OUT_METHOD varchar(100),
    DYARD_OUT_DATE datetime,
    VYARD_OUT_REMARK varchar(1000),
    IYARD_OUT_BY int,
    DYARD_OUT_AT datetime,
    VLEGAL_OBJECTION varchar(10),
    BM_OBJECTION_ADDEDDBY decimal(20, 0),
    BM_OBJECTION_ADDEDDATE datetime2,
    I12IVCONFIRMATION_ADDEDDBY decimal(20, 0),
    D12IVCONFIRMATION_ADDEDDATE datetime2,
    LEGAL_OBJECTION_ADDEDDBY decimal(20, 0),
    LEGAL_OBJECTION_ADDEDDATE datetime2,
    VAPPROVED smallint,
    VAPPROVALLEVEL1 smallint,
    IAPPROVALLEVEL1USER int,
    VLEVEL1REMARK varchar(1000),
    IAPPROVALLEVEL1DATE datetime2,
    VAPPROVALLEVEL2 smallint,
    IAPPROVALLEVEL2USER int,
    VLEVEL2REMARK varchar(1000),
    IAPPROVALLEVEL2DATE datetime2,
    VAPPROVALLEVEL3 smallint,
    IAPPROVALLEVEL3USER int,
    VLEVEL3REMARK varchar(1000),
    IAPPROVALLEVEL3DATE datetime2,
    VAPPROVALFINAL smallint,
    IAPPROVALFINALUSER int,
    VFINALREMARK varchar(1000),
    IAPPROVALFINALDATE datetime2,
    IDELIND smallint,
    IPUBLISH smallint,
    IADDEDBY decimal(20, 0),
    DADDEDDATE datetime2,
    IUPDATEDBY decimal(20, 0),
    DUPDATEDDATE datetime2,
    DDELETEDDATE datetime2,
    VURL varchar(1000),

);






