CREATE TABLE TBL_CORE_CONTRACT_INFO (
    LOAN_MASTER_ID varchar(45),
    PRODUCT_ID varchar(20),
    SUB_PRODUCT_ID varchar(20),
    V_SEQUENCE varchar(10),
    MAIN_ACCOUNT_NO varchar(45),
    PRIMARY_CUS_ID varchar(20),
    SECONDORY_CUS_ID varchar(20),
    MAIN_FACILITY_NO varchar(45),
    CONTRACT_NO varchar(45),
    OLD_CONTRACT_NO varchar(45),
    LAST_LETTER_ISSUED date,
    TC_ID varchar(45),
    LOAN_APPLY_DATE date,
    LOAN_APPLY_AMOUNT int,
    LOAN_APPROVE_DATE date,
    LOAN_APPROVE_AMOUNT decimal(20, 2),
    LOAN_TERM int,
    MATURE_DATE varchar(50),
    TRUE_RATE decimal(20, 2),
    INSTALLMENT_AMOUNT bigint,
    PURPOSE varchar(500),
    ACCOUNT_OPEN_DATE varchar(50),
    FIRST_DISBURSEMENT_DATE varchar(50),
    LOAN_PAYMENT_METHOD varchar(10),
    CLOSED_DATE date,
    CLOSED_REASON varchar(500),
    RENT_DUE_DATE varchar(50),
    MAIN_BRANCH_ID varchar(10),
    ALLOCATION_BRANCH_ID varchar(10),
    STATUS char(2),
    IS_WRITE_OFF char(1),
    LAST_UPDATED_DATE date,
    LAST_EXTRACTED_DATE date,
    DATE_CREATED date,
    SEGMENT varchar(50),
    SEGMENT_TYPE varchar(50),
    MORATORIUM char(1),
    DAYS_PASTDUE int,
    CURRENCY varchar(50),
    ILOAN_AMOUNT decimal(20, 2),
    RESHEDULE_FLAG varchar(50),
    NEXT_INSTALLMENT_DATE varchar(45),
    NEXT_INSTALLMENT_AMOUNT decimal(20, 2),
    NEXT_INSTALLMEN_TYPE varchar(45),
    OFFICE_CODE varchar(100),
    MORATORIUM_CODE varchar(100),
    NPA_FLAG varchar(100),
    DAILY_FACTOR varchar(50),
    LATE_FEES int,
    PRINCIPAL varchar(100),
    TRAN_DESCRIPTION varchar(100),
    MATURITY_PERIOD varchar(100),
    REFERENCE_LC varchar(100),
    INVOICE_NO varchar(100),
    PRODUCT varchar(100),
    CIF varchar(100),
    CARD_ACC_TYPE varchar(50),
    MAS_CARD varchar(50),
    ACCOUNT1 varchar(50),
    BILLING_CYCLE_CODE varchar(50),
    ACC_STATUS varchar(50),
    CITIZEN_ID varchar(50),
    DIRECT_DEBIT_PYMNT_ACC varchar(50),
    PAYMENT_CODE varchar(50),
    LAST_PAYMENT decimal(20, 2),
    LAST_PAYMENT_DATE varchar(50),
    MINIMUM_PAYMENT decimal(20, 2),
    EXPIRED_PAYMENTS decimal(20, 2),
    APP_APPROVAL_DATE date,
    BRANCH_OFFICE_CODE varchar(50),
    FUTURE_PYMNT_DUE_DATE date,
    CARD_STATUS varchar(50),
    FIELD4 varchar(50),
    VIP_PROFILE varchar(50),
    OCCU_CODE varchar(50),
    MOTHERS_MAIDEN_NAME varchar(50),
    MILITARY_BRANCH varchar(50),
    INCOME_1 decimal(20, 2),
    INCOME_2 decimal(20, 2),
    EMAIL varchar(50),
    CLIENT_ID varchar(50),
    SCH_NAME varchar(50),
    LAST_PAYMENT_AMOUNT decimal(18, 3),
    LAST_DUE_DATE date,
    VLAST_PAYMENT_DATE date,
    OLDEST_DUE_DATE date,
    USER_CODE1 char(1),
    DEPOSITS varchar(100),
    DESTINATION_ACC varchar(100),
    INTEREST_SUS_CURR decimal(18, 3),
    NOTE_NO varchar(100),
    PAY_OFF_BALANCE decimal(18, 3),
    PAY_ACC_NO varchar(100),
    RECOVERY_STATUS varchar(10),
    OVERDUE_MONTHS varchar(40),
    FUTURE_RENTALS decimal(18, 3),

);






