CREATE TABLE TBL_C_WK_STEP (
    IID numeric(20, 0),
    IWKMAINID numeric(20, 0),
    ISETSTEPCODE varchar(4000),
    IORDER numeric(20, 0),
    ISTEPTYPE varchar(500),
    IPARENTSTEPID numeric(20, 0),
    IPATHINDICATOR numeric(20, 0),
    ILEVELID numeric(20, 0),
    IUSERID numeric(20, 0),
    IGROUPID numeric(20, 0),
    ISUSERRULE numeric(20, 0),
    ISETFORMID numeric(20, 0),
    IISMANDATORY numeric(20, 0),
    ISETACTIONIDS varchar(4000),
    ISETTEMPLATEID numeric(20, 0),
    IDATAFORMIDS varchar(4000),
    IUSERLINKEDSTEPID numeric(20, 0),
    IREOPENSTEPID numeric(20, 0),
    IMTNSUBJECT varchar(4000),
    IMTNDESC varchar(4000),
    IMTNLOCATION varchar(4000),
    DMTNDATE datetime2,
    DMTNTIME datetime2,
    IPARALLELSTEPS varchar(4000),
    IYESSTEPID numeric(20, 0),
    INOSTEPID numeric(20, 0),
    IFROMSTEPOPTION numeric(20, 0),
    IESTHOURS numeric(20, 2),
    IESKLEVELID numeric(20, 0),
    IESKUSERID numeric(20, 0),
    IESKGROUPID numeric(20, 0),
    ISESKUSERRULE numeric(20, 0),
    IESKEMAILTEMPLATEID numeric(20, 0),
    IESKSMSTEMPLATEID numeric(20, 0),
    VDESC varchar(4000),
    IDELIND numeric(1, 0),
    DDELETEDDATE datetime2,
    IPUBLISH numeric(1, 0),
    IADDEDBY numeric(20, 0),
    DADDEDDATE datetime2,
    IUPDATEDBY numeric(20, 0),
    DUPDATEDATE datetime2,
    VURL varchar(1000),
    IFUNCTIONCALLID numeric(20, 0),
    STEPNAME varchar(2000),

);






